trigger:
  - main  # Runs the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Uses Ubuntu for the build agent

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'  # Specify the required Java version
      jdkArchitectureOption: 'x64'  # This fixes the error
      jdkSourceOption: 'PreInstalled'  # Or use 'AzureStorage' if downloading from Azure Storage

  - script: |
      echo "Setting up Maven"
      mvn --version
    displayName: 'Verify Maven Installation'

  - script: |
      echo "Running tests with Maven"
      mvn clean test
    displayName: 'Run REST Assured Tests'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      publishJUnitResults: true
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      mavenVersionOption: 'Default'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'  # Collects JUnit test results
      testRunTitle: 'REST Assured Tests'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'target/surefire-reports'  # Uploads test reports
      artifactName: 'TestReports'
