trigger:
  - main  # Runs the pipeline on commits to the main branch

variables:
  JAVA_VERSION: '17'
  MAVEN_GOALS: 'clean test'
  TEST_RESULTS_PATH: '**/target/surefire-reports/TEST-*.xml'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndTest
    timeoutInMinutes: 10  # ✅ Correct placement inside a job
    steps:
      - script: echo "Running tests"
      
steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '$(JAVA_VERSION)'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: |
      echo "Setting up Maven"
      mvn --version
    displayName: 'Verify Maven Installation'

  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | pom.xml'
      path: ~/.m2/repository
      restoreKeys: |
        maven | "$(Agent.OS)"

  - script: |
      echo "Running tests with Maven"
      mvn $(MAVEN_GOALS) -T 4
    displayName: 'Run REST Assured Tests'

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: '$(MAVEN_GOALS)'
      publishJUnitResults: true
      testResultsFiles: '$(TEST_RESULTS_PATH)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '$(JAVA_VERSION)'
      mavenVersionOption: 'Default'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '$(TEST_RESULTS_PATH)'
      testRunTitle: 'REST Assured Tests'
    condition: succeededOrFailed()

  - script: |
      mvn surefire-report:report-only
    displayName: 'Generate HTML Test Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'target/site/surefire-report.html'
      artifactName: 'HTML-TestReport'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/logs'
      artifactName: 'Logs'
    condition: failed()

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        if ("$(Build.Status)" -ne "Succeeded") {
          Write-Host "##vso[task.logissue type=error]Build failed! Notify the team."
        }
    condition: failed()
